#ifndef TOKENS_H
#define TOKENS_H

enum TokenType {
    IF = 256, ELSE, FOR, WHILE, RETURN, GOTO, BREAK, CONTINUE,
    SWITCH, CASE, DEFAULT, STRUCT, TYPEDEF, STATIC, CONST, AUTO,
    CLASS, PRIVATE, PROTECTED, PUBLIC, LAMBDA,
    INT, CHAR, FLOAT, DOUBLE, VOID, SIGNED_INT, UNSIGNED_INT,
    IDENTIFIER, INT_LITERAL, FLOAT_LITERAL, STRING_LITERAL, CHAR_LITERAL,
    PLUS, MINUS, MUL, DIV, MOD,
    EQ, NEQ, LT, GT, LEQ, GEQ,
    AND, OR, NOT,
    BIT_AND, BIT_OR, BIT_XOR, BIT_NOT,
    INC, DEC,
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    COLON, SEMICOLON, COMMA, ASSIGN,
    ERROR
};

#endif
